root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/api"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin","logs","postgres"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "./tmp/main"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500

[color]
app_output = ""
build_log_cmd_output = ""
build_log_main_output = ""
main_output = ""
time = ""

[log]
main_only = false
time = false

[misc]
clean_on_exit = false
